<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <properties>
        <maven.build.timestamp.format>yyyyMMdd-HHmm</maven.build.timestamp.format>
        <packaging.type>jar</packaging.type>
        <build.min.memory>-Xms128m</build.min.memory>
        <build.max.memory>-Xmx2048m</build.max.memory>
    </properties>

    <parent>
        <artifactId>forge</artifactId>
        <groupId>forge</groupId>
        <version>${revision}</version>
    </parent>

    <artifactId>forge-gui-ios</artifactId>
    <packaging>${packaging.type}</packaging>
    <name>Forge iOS</name>

    <build>
        <sourceDirectory>src</sourceDirectory>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>17</source>
                    <target>17</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.mobidevelop.robovm</groupId>
                <artifactId>robovm-maven-plugin</artifactId>
                <version>2.3.24</version>
                <configuration>
                    <propertiesFile>robovm.properties</propertiesFile>
                    <configFile>robovm.xml</configFile>
                    <iosInfoPList>Info.plist.xml</iosInfoPList>
                    <iosSkipSigning>true</iosSkipSigning>
                </configuration>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>filters</directory>
                <filtering>true</filtering>
            </resource>
            <resource>
                <directory>.</directory>
                <includes>
                    <include>fallback_skin/**</include>
                </includes>
            </resource>
        </resources>
        <finalName>forge-ios-${revision}</finalName>
    </build>

    <dependencies>
        <dependency>
            <groupId>forge</groupId>
            <artifactId>forge-core</artifactId>
            <version>2.0.08-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>io.sentry</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>forge</groupId>
            <artifactId>forge-game</artifactId>
            <version>2.0.08-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>io.sentry</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>forge</groupId>
            <artifactId>forge-ai</artifactId>
            <version>2.0.08-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>io.sentry</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>forge</groupId>
            <artifactId>forge-gui</artifactId>
            <version>2.0.08-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>org.jupnp</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.eclipse.jetty</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.sentry</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>forge</groupId>
            <artifactId>forge-gui-mobile</artifactId>
            <version>2.0.08-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>org.jupnp</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.eclipse.jetty</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.sentry</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.badlogicgames.gdx</groupId>
            <artifactId>gdx-backend-robovm</artifactId>
            <version>1.13.5</version>
        </dependency>
        <dependency>
            <groupId>com.badlogicgames.gdx</groupId>
            <artifactId>gdx-platform</artifactId>
            <version>1.13.5</version>
            <classifier>natives-ios</classifier>
        </dependency>
        <dependency>
            <groupId>com.badlogicgames.gdx</groupId>
            <artifactId>gdx-freetype</artifactId>
            <version>1.13.5</version>
        </dependency>
        <dependency>
            <groupId>com.badlogicgames.gdx</groupId>
            <artifactId>gdx-freetype-platform</artifactId>
            <version>1.13.5</version>
            <classifier>natives-ios</classifier>
        </dependency>
    </dependencies>
</project>
