#
#Wed Dec 03 21:31:22 CET 2014
app.version=1.0
app.id=com.mathforthemasses.forge.ios
app.mainclass=forge.ios.Main
app.executable=forge.ios.Main
app.build=18
app.name=Forge

# Set timezone before JVM initialization to avoid iOS sandbox violations
robovm.jvmArgs=-Duser.timezone=America/Los_Angeles
